{
    "source_graph": {
        "class": "File",
        "path": "StackCreation.xml"
    },
    "file_type": "GeoTIFF",
    "source_product": [
        {
            "path": "/data/images/optic/S2A_MSIL1C_20180610T154901_N0206_R054_T18TXR_20180610T193029.SAFE/MTD_MSIL1C.xml",
            "class": "File",
            "secondaryFiles": [
                {
                    "class": "Directory",
                    "path": "/data/images/optic/S2A_MSIL1C_20180610T154901_N0206_R054_T18TXR_20180610T193029.SAFE/AUX_DATA"
                },
                {
                    "class": "Directory",
                    "path": "/data/images/optic/S2A_MSIL1C_20180610T154901_N0206_R054_T18TXR_20180610T193029.SAFE/DATASTRIP"
                },
                {
                    "class": "Directory",
                    "path": "/data/images/optic/S2A_MSIL1C_20180610T154901_N0206_R054_T18TXR_20180610T193029.SAFE/GRANULE"
                },
                {
                    "class": "Directory",
                    "path": "/data/images/optic/S2A_MSIL1C_20180610T154901_N0206_R054_T18TXR_20180610T193029.SAFE/HTML"
                },
                {
                    "class": "Directory",
                    "path": "/data/images/optic/S2A_MSIL1C_20180610T154901_N0206_R054_T18TXR_20180610T193029.SAFE/rep_info"
                },
                {
                    "class": "File",
                    "path": "/data/images/optic/S2A_MSIL1C_20180610T154901_N0206_R054_T18TXR_20180610T193029.SAFE/INSPIRE.xml"
                },
                {
                    "class": "File",
                    "path": "/data/images/optic/S2A_MSIL1C_20180610T154901_N0206_R054_T18TXR_20180610T193029.SAFE/manifest.safe"
                },
            ]
        },
        {
            "path": "/data/images/radar/S1A_IW_GRDH_1SDV_20170413T224356_20170413T224421_016132_01AA52_90ED.SAFE/manifest.safe",
            "class": "File",
            "secondaryFiles": [
                {
                    "class": "Directory",
                    "path": "/data/images/radar/S1A_IW_GRDH_1SDV_20170413T224356_20170413T224421_016132_01AA52_90ED.SAFE/annotation"
                },
                {
                    "class": "Directory",
                    "path": "/data/images/radar/S1A_IW_GRDH_1SDV_20170413T224356_20170413T224421_016132_01AA52_90ED.SAFE/measurement"
                },
                {
                    "class": "Directory",
                    "path": "/data/images/radar/S1A_IW_GRDH_1SDV_20170413T224356_20170413T224421_016132_01AA52_90ED.SAFE/preview"
                },
                {
                    "class": "Directory",
                    "path": "/data/images/radar/S1A_IW_GRDH_1SDV_20170413T224356_20170413T224421_016132_01AA52_90ED.SAFE/support"
                },
                {
                    "class": "File",
                    "path": "/data/images/radar/S1A_IW_GRDH_1SDV_20170413T224356_20170413T224421_016132_01AA52_90ED.SAFE/S1A_IW_GRDH_1SDV_20170413T224356_20170413T224421_016132_01AA52_90ED.SAFE-report-20170414T033350.pdf"
                }
            ]
        },
        {
            "path": "/data/images/radar/RS2_OK18072_PK188251_DK178156_F22_20090501_110525_HH_HV_SLC/product.xml",
            "class": "File",
            "secondaryFiles": [
                {
                    "class": "Directory",
                    "path": "/data/images/radar/RS2_OK18072_PK188251_DK178156_F22_20090501_110525_HH_HV_SLC/schemas"
                },
                {
                    "class": "File",
                    "path": "/data/images/radar/RS2_OK18072_PK188251_DK178156_F22_20090501_110525_HH_HV_SLC/BrowseImage.tif"
                },
                {
                    "class": "File",
                    "path": "/data/images/radar/RS2_OK18072_PK188251_DK178156_F22_20090501_110525_HH_HV_SLC/imagery_HH.tif"
                },
                {
                    "class": "File",
                    "path": "/data/images/radar/RS2_OK18072_PK188251_DK178156_F22_20090501_110525_HH_HV_SLC/imagery_HV.tif"
                },
                {
                    "class": "File",
                    "path": "/data/images/radar/RS2_OK18072_PK188251_DK178156_F22_20090501_110525_HH_HV_SLC/lutBeta.xml"
                },
                {
                    "class": "File",
                    "path": "/data/images/radar/RS2_OK18072_PK188251_DK178156_F22_20090501_110525_HH_HV_SLC/lutGamma.xml"
                },
                {
                    "class": "File",
                    "path": "/data/images/radar/RS2_OK18072_PK188251_DK178156_F22_20090501_110525_HH_HV_SLC/lutSigma.xml"
                },
                {
                    "class": "File",
                    "path": "/data/images/radar/RS2_OK18072_PK188251_DK178156_F22_20090501_110525_HH_HV_SLC/readme.txt"
                },
                {
                    "class": "File",
                    "path": "/data/images/radar/RS2_OK18072_PK188251_DK178156_F22_20090501_110525_HH_HV_SLC/RS2_TC.tif"
                },
            ]
        }
    ],
    "output_name": "stack_result.tif"
}
