# label rules used by labelers to match words
# references:
#   - https://github.com/github/issue-labeler


feature/CWL:
  - '(CWL|cwl)'
  - 'workflow'

feature/oas:
  - '(OpenAPI|openapi)'
  - '(Swagger|swagger)'
  - cornice
  - colander

feature/docker:
  - '(Docker|docker)'

process/wps1:
  - 'WPS-1'
  - 'WPS1'

process/wps2:
  - 'WPS-2'
  - 'WPS2'

process/wps3:
  - 'WPS-3'
  - 'WPS3'
  - 'WPS-REST'
  - 'rest bindings'
  - 'OGC API - Processes'
  - 'OGC-API-Processes'

process/esgf-cwt:
  - 'ESGF'
  - 'ESGF-CWT'

process/workflow:
  - 'workflow'

triage/conformance:
  - 'conforms'
  - 'conformance'
  - 'complies'
  - 'compliance'

triage/feature:
  - 'feature'

triage/bug:
  - 'bug'

ci/operations:
  - 'ci'
  - 'travis'
  - 'github'

ci/tests:
  - 'coverage'
  - 'functional test[s]*'
  - 'unittest[s]*'

ci/doc:
  - 'documentation'
  - 'readthedocs'
  - 'rtd'
