# label rules used by PR labelers to match repository files
# references:
#   original: https://github.com/actions/labeler
#   extended: https://github.com/ilyam8/periodic-pr-labeler

## CI
# all automation-related steps and files

ci/operations:
  - .*  # all '.<>' files
  - ".github/**"
  - MANIFEST.in
  - hooks/**/*
  - Makefile*
  - Dockerfile*
  - setup.*
  - requirements*
  - tests/smoke/**/*

ci/doc:
  - "*.rst"
  # ignore changelog as doc would almost always be tagged
  - "!CHANGES.rst"
  - "*.example"
  - LICENCE*
  - docs/**/*
  - weaver/wps_restapi/api.py
  - weaver/wps_restapi/colander_extras.py
  - weaver/wps_restapi/swagger_definitions.py
  - weaver/wps_restapi/templates/swagger_ui.mako

ci/tests:
  - tests/**/*
  - weaver/processes/wps_default.py
  - weaver/processes/wps_testing.py

## Triage

triage/security:
  - weaver/visibility.py
  - SECURITY.rst

## Features
# specific components of the code base

feature/db:
  - weaver/datatype.py
  - weaver/database/**/*
  - weaver/store/**/*
  - weaver/sort.py

feature/oas:
  - weaver/wps_restapi/templates/swagger_ui.mako
  - weaver/wps_restapi/colander_extras.py
  - weaver/wps_restapi/swagger_definitions.py

feature/CWL:
  - weaver/processes/wps_process_base.py
  - weaver/processes/wps_package.py
  - weaver/processes/wps_workflow.py

feature/opensearch:
  - weaver/processes/opensearch.py

# -- Files that *always* impact jobs --
feature/job:
  - weaver/execute.py
  - weaver/sort.py
  - weaver/wps_restapi/jobs/**/*
  - weaver/wps_restapi/templates/notification_email_example.mako

## -- WPS processes --

process/builtin:
  - weaver/processes/builtin/**/*

process/wps1:
  - weaver/wps.py
  - weaver/processes/wps1*

process/wps2:
  - weaver/wps.py
  - weaver/processes/wps2*

process/wps3:
  - weaver/wps_restapi/**/*

process/esgf-cwt:
  - weaver/processes/esgf*

process/workflow:
  - weaver/processes/wps_workflow.py
