# configuration to setup readthedocs
version: 2
sphinx:
  configuration: docs/source/conf.py
#formats: all
formats:
  - htmlzip
python:
  version: "3.7"
  install:
    - requirements: requirements-rtd.txt
    # - requirements: requirements-sys.txt
    - requirements: requirements-doc.txt
  system_packages: false
