# configuration to setup readthedocs
version: 2
sphinx:
  configuration: docs/source/conf.py
#formats: all
formats:
  - htmlzip
python:
  version: "3.8"
  install:
    - requirements: requirements-sys.txt
    - requirements: requirements-doc.txt
