# configuration to setup readthedocs
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
sphinx:
  configuration: docs/source/conf.py
#formats: all
formats:
  - htmlzip
python:
  install:
    - requirements: requirements-sys.txt
    - requirements: requirements-doc.txt
