# vim:set ft=dockerfile:
FROM birdhouse/bird-base:latest
MAINTAINER "francis.charette-migneault@crim.ca"

LABEL Description="Weaver" Vendor="CRIM"

# Configure hostname and ports for services
ENV HTTP_PORT 8080
ENV HTTPS_PORT 8443
ENV OUTPUT_PORT 8000
ENV HOSTNAME localhost
ENV WEAVER_URL weaver
ENV WEAVER_WPS_RESTAPI_PATH /
# Set conda enviroment
ENV ANACONDA_HOME /opt/conda
ENV CONDA_ENV weaver
ENV CONDA_ENVS_DIR /opt/conda/envs
# Set current home
ENV HOME /root
# Start supervisor in foreground
ENV DAEMON_OPTS --nodaemon

# Ports used in birdhouse
EXPOSE 9001 $HTTP_PORT $HTTPS_PORT $OUTPUT_PORT

# cd into application
WORKDIR /opt/birdhouse/src/weaver

# Volume for data, cache, logfiles, configs
VOLUME /opt/birdhouse/var/lib
VOLUME /opt/birdhouse/var/log
VOLUME /opt/birdhouse/etc

# Create folders required for installation and fix permissions
RUN mkdir -p /opt/birdhouse/etc && \
    mkdir -p /opt/birdhouse/var/run && \
    mkdir -p /opt/birdhouse/var/tmp/nginx/client && \
    chmod 755 /opt/birdhouse/etc && \
    chmod 755 /opt/birdhouse/var/run

# Provide custom.cfg with settings for docker image
RUN printf "[buildout]\nextends=buildout.cfg profiles/docker.cfg" > custom.cfg

COPY Makefile requirements.sh bootstrap.sh ./

# Install system dependencies and Anaconda
RUN make install-sys anaconda

# Copy files for buildout setup and requirements
COPY buildout.cfg requirements*.txt ./
COPY profiles ./profiles/

# setup Anaconda environment and setup buildout
#   files generated by buildout are skipped in .dockerignore
#   files created from install process must be removed
#   also clean extra caches from pip
RUN make bootstrap install-base && \
    make clean-bld clean-cache clean-src && \
    rm -rf /root/.cache

# Copy application sources
COPY . /opt/birdhouse/src/weaver

# install without dependencies (pre-installed)
RUN make install-raw

CMD ["make", "online-update-config", "start"]
