# vim:set ft=dockerfile:
FROM debian:latest
LABEL Description="Weaver" Vendor="CRIM" Maintainer="francis.charette-migneault@crim.ca"

# Configure hostname and ports for services
ENV HTTP_PORT 8080
ENV HTTPS_PORT 8443
ENV OUTPUT_PORT 8000
ENV HOSTNAME localhost
ENV WEAVER_URL weaver
# Set conda enviroment
ENV CONDA_HOME /opt/conda
ENV CONDA_ENV weaver
ENV CONDA_ENVS_DIR /opt/conda/envs
# Set current home
ENV HOME /root
# Start supervisor in foreground
ENV DAEMON_OPTS --nodaemon
WORKDIR /opt/birdhouse/src/weaver

# Ports used in birdhouse
EXPOSE 9001 $HTTP_PORT $HTTPS_PORT $OUTPUT_PORT

# Volume for data, cache, logfiles, configs
VOLUME /opt/birdhouse/var/lib
VOLUME /opt/birdhouse/var/log
VOLUME /opt/birdhouse/etc

# Create folders required for installation and fix permissions
RUN mkdir -p /opt/birdhouse/var/run && \
    mkdir -p /opt/birdhouse/var/tmp/nginx/client && \
    chmod 755 /opt/birdhouse/var/run

# Provide custom.cfg with settings for docker image
RUN printf "[buildout]\nextends=buildout.cfg profiles/docker.cfg" > custom.cfg

# Copy files for buildout setup and requirements
COPY Makefile buildout.cfg requirements*.txt setup.py weaver/__meta__.py ./
COPY profiles ./profiles/
COPY templates ./templates/

RUN apt-get update --fix-missing && \
    # install dependencies to run scripts
    apt-get install -y \
        ca-certificates \
        bzip2 \
        gcc \
        make \
        wget \
        curl \
        openssl \
        libssl-dev \
        libffi-dev \
        libxml2-dev \
        libxslt1-dev \
        libyaml-dev \
        && \
    # install requirements, conda environment and setup with buildout
    make bootstrap conda conda-env install && \
    # files generated by buildout are skipped in .dockerignore
    # files created from install process must be removed
    make clean-bld clean-cache clean-src && \
    apt-get clean

# Copy application sources
COPY . /opt/birdhouse/src/weaver

# install without dependencies (pre-installed)
RUN make install-raw

CMD ["make", "online-update-config", "start"]
