PATCH /processes/test-process:1.2.3 HTTP/1.1
Host: weaver.example.com
Content-Type: application/json

{
  "description": "new description",
  "inputs": {
    "input": {
      "description": "modified input description"
    },
    "outputs": {
      "output": {
        "title": "modified title"
      }
    }
  }
}
