source_graph:
  class: File
  path: StackCreation.xml
file_type: BEAM-DIMAP
source_product:
  class: File
  path: E:\ProjetAyoub\Image Optique\S2A_MSIL1C_20180610T154901_N0206_R054_T18TXR_20180610T193029.SAFE\MTD_MSIL1C.xml
  #TODO: Comment passer les fichiers supplémentaires: E:\ProjetAyoub\IMAGES RADAR\Sentinel1\New Folder\S1A_IW_GRDH_1SDV_20170413T224356_20170413T224421_016132_01AA52_90ED.SAFE\manifest.safe,E:\ProjetAyoub\IMAGES RADAR\RADARSAT-2\RS2_OK18072_PK188251_DK178156_F22_20090501_110525_HH_HV_SLC\product.xml
output_name: Resultat_Stack.dim
