FROM weaver-base:0.2.2
LABEL description.short="Weaver Manager"

# python 2, gunicorn 19.x
# gunicorn --paste "${APP_CONFIG_DIR}/weaver.ini" --preload
# python >=3.5, gunicorn 20.x
CMD pserve "${APP_CONFIG_DIR}/weaver.ini"
