FROM weaver:base
LABEL description.short="Weaver Worker"

# NOTE: only worker should be using docker, manager is only for API
RUN apt-get update && apt-get install -y --no-install-recommends \
		docker-ce \
		docker-ce-cli \
		containerd.io \
	&& rm -rf /var/lib/apt/lists/*

# run app
CMD celery worker -A pyramid_celery.celery_app --ini "${APP_CONFIG_DIR}/weaver.ini"
