EXECUTE_MODE_AUTO = "auto"
EXECUTE_MODE_ASYNC = "async"
EXECUTE_MODE_SYNC = "sync"

EXECUTE_MODE_OPTIONS = frozenset([
    EXECUTE_MODE_AUTO,
    EXECUTE_MODE_ASYNC,
    EXECUTE_MODE_SYNC,
])

EXECUTE_CONTROL_OPTION_ASYNC = "async-execute"
EXECUTE_CONTROL_OPTION_SYNC = "sync-execute"

EXECUTE_CONTROL_OPTIONS = frozenset([
    EXECUTE_CONTROL_OPTION_ASYNC,
    EXECUTE_CONTROL_OPTION_SYNC,
])

EXECUTE_RESPONSE_RAW = "raw"
EXECUTE_RESPONSE_DOCUMENT = "document"

EXECUTE_RESPONSE_OPTIONS = frozenset([
    EXECUTE_RESPONSE_RAW,
    EXECUTE_RESPONSE_DOCUMENT,
])

EXECUTE_TRANSMISSION_MODE_VALUE = "value"
EXECUTE_TRANSMISSION_MODE_REFERENCE = "reference"

EXECUTE_TRANSMISSION_MODE_OPTIONS = frozenset([
    EXECUTE_TRANSMISSION_MODE_VALUE,
    EXECUTE_TRANSMISSION_MODE_REFERENCE,
])
