PROCESS_WPS = "wps"
PROCESS_TEST = "test"
PROCESS_APPLICATION = "application"
PROCESS_WORKFLOW = "workflow"
PROCESS_BUILTIN = "builtin"

PROCESS_WITH_MAPPING = frozenset([PROCESS_BUILTIN, PROCESS_APPLICATION, PROCESS_WORKFLOW, PROCESS_TEST])
