name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      continue-on-error: true
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >
          Thanks for submitting an issue.

          Make sure you have checked through existing/resolved issues to avoid duplicates.
          Also, make sure you provide enough details for us to be able to replicate and understand the problem.
        pr-message: >
          Thanks for submitting a PR.

          Make sure that you have added tests to validates new features or bugfixes.
          Also, ensure that existing test suites are still working with the change using the commit test statuses.
