# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Pull Request Labeler
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  schedule:
    - cron: '*/10 * * * *'

jobs:
  original-labeler:
    # reference: https://github.com/actions/labeler
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        configuration-path: .github/labeler-files.yml
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
  extended-labeler:
    # reference: https://github.com/ilyam8/periodic-pr-labeler
    runs-on: ubuntu-latest
    steps:
      - uses: docker://docker.io/ilyam8/periodic-pr-labeler:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LABEL_MAPPINGS_FILE: .github/labeler-files.yml
  wip:
    # reference: https://github.com/wip/action
    # mark PRs with 'WIP' in title as pending
    # then, block merge of these branches using [settings->branches->master->status check with 'WIP' action]
    if: ${{ github.event_name == 'pull_request' }}  # WIP only works during PRs
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: wip/action@v1
